### ISSUE TITLE
Handle repeat arguments in steps

### ISSUE THREAD

**Issue by camargo** [NASA-AMMOS/seq-json-schema#1]
This is to add arrays to the [args](https://github.com/NASA-AMMOS/seq-json-schema/blob/develop/schema.json#L46) to handle repeat arguments. For example for a command step this would look something like:

```json
{
  "stem": "FAKE_COMMAND1",
  "args": [
    { "hex": "0xFFFFFFFF" },
    [
      [0, 1],
      [0, 1]
    ]
  ],
  "time": { "type": "COMMAND_COMPLETE" },
  "type": "command"
}
```

Where the second argument is a repeat arg with two repeating arguments, each consisting of two number arguments. The first argument is not a repeat arg.

**Comment by cohansen** [comment]
Due to the changes in #3 would this actually become:
```json
{
  "stem": "FAKE_COMMAND1",
  "args": [
    { "hex": "0xFFFFFFFF" },
    [
      [{ "number": 0 }, { "number": 1 }],
      [{ "number": 0 }, { "number": 1 }]
    ]
  ],
  "time": { "type": "COMMAND_COMPLETE" },
  "type": "command"
}
```

Or are we handling repeat args differently?

**Comment by camargo** [comment]
@cohansen Yeah I think that's correct. Or maybe:

```json
{
  "stem": "FAKE_COMMAND1",
  "args": [
    { "hex": "0xFFFFFFFF" },
    {
      "repeat": [
        [{ "number": 0 }, { "number": 1 }],
        [{ "number": 0 }, { "number": 1 }]
      ]
    }
  ],
  "time": { "type": "COMMAND_COMPLETE" },
  "type": "command"
}
```
