### ISSUE TITLE
Enforce repeat arg arrays have the same types

### ISSUE THREAD

**Issue by camargo** [NASA-AMMOS/seq-json-schema#11]
Currently the schema allows the following:

```json
{
  "type": "repeat",
  "value": [
    [
      { "type": "number", "value": 10 },
      { "type": "string", "value": "another_test" },
      { "type": "boolean", "value": false }
    ],
    [
      { "type": "string", "value": "5" },
      { "type": "string", "value": "repeat_test" },
      { "type": "boolean", "value": true }
    ]
  ]
}
```

This is objectively wrong. Can we enforce each inner-array has the same set of types (in order)? Not sure if this is possible.

**Comment by cohansen** [comment]
I think you're right and this isn't possible. I did a little research this morning to see if there are any hacks / workarounds but I can't find anything.

**Comment by camargo** [comment]
Closing. This does not seem possible with JSON schema.
